"""add agent_processes session_id

Revision ID: 130b09d5d131
Revises: f55def878cac
Create Date: 2026-07-10 11:31:44.854411

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "130b09d5d131"
down_revision: str | Sequence[str] | None = "f55def878cac"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("agent_processes", schema=None) as batch_op:
        batch_op.add_column(sa.Column("session_id", sa.String(length=64), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("agent_processes", schema=None) as batch_op:
        batch_op.drop_column("session_id")

    # ### end Alembic commands ###
