"""Story1 add goals themes phases tasks drafts

Revision ID: b2e0af769c6a
Revises:
Create Date: 2026-07-09 11:30:35.792546

"""

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "b2e0af769c6a"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "drafts",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("user_id", sa.String(length=64), nullable=False),
        sa.Column("story_type", sa.String(length=16), nullable=False),
        sa.Column("entity_id", sa.String(length=36), nullable=True),
        sa.Column("content", sa.Text(), nullable=False),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column("expires_at", sa.DateTime(), nullable=True),
        sa.CheckConstraint(
            "status IN ('pending','confirmed','expired','discarded')", name="ck_drafts_status"
        ),
        sa.CheckConstraint(
            "story_type IN ('plan','schedule','daily','weekly','edit','config')",
            name="ck_drafts_story_type",
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "goals",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("time_range_start", sa.Date(), nullable=True),
        sa.Column("time_range_end", sa.Date(), nullable=True),
        sa.Column("scheduled_start_date", sa.Date(), nullable=True),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.Column("status_changed_at", sa.DateTime(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "status IN ('未开始','进行中','已完成','已暂停')", name="ck_goals_status"
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("name"),
    )
    op.create_table(
        "themes",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("goal_id", sa.String(length=36), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("type", sa.String(length=16), nullable=False),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.Column("status_changed_at", sa.DateTime(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "status IN ('未开始','进行中','已完成','已暂停')", name="ck_themes_status"
        ),
        sa.CheckConstraint(
            "type IN ('learning','research','source','dev','survey')", name="ck_themes_type"
        ),
        sa.ForeignKeyConstraint(
            ["goal_id"],
            ["goals.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "phases",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("theme_id", sa.String(length=36), nullable=False),
        sa.Column("sort_order", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.Column("status_changed_at", sa.DateTime(), nullable=True),
        sa.Column("deadline", sa.Date(), nullable=True),
        sa.Column("activated_at", sa.Date(), nullable=True),
        sa.Column("completed_at", sa.DateTime(), nullable=True),
        sa.Column("paused_at", sa.DateTime(), nullable=True),
        sa.CheckConstraint(
            "status IN ('未开始','进行中','已完成','已暂停')", name="ck_phases_status"
        ),
        sa.ForeignKeyConstraint(
            ["theme_id"],
            ["themes.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("theme_id", "sort_order", name="uq_phases_theme_sort"),
    )
    op.create_table(
        "tasks",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("phase_id", sa.String(length=36), nullable=False),
        sa.Column("sort_order", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.Column("status_changed_at", sa.DateTime(), nullable=True),
        sa.Column("executor", sa.String(length=16), nullable=True),
        sa.Column("has_subtask", sa.Boolean(), nullable=False),
        sa.Column("retry_count", sa.Integer(), nullable=False),
        sa.Column("completed_at", sa.DateTime(), nullable=True),
        sa.Column("paused_at", sa.DateTime(), nullable=True),
        sa.CheckConstraint(
            "executor IS NULL OR executor IN ('human','agent')", name="ck_tasks_executor"
        ),
        sa.CheckConstraint("status IN ('待执行','已完成','已暂停')", name="ck_tasks_status"),
        sa.ForeignKeyConstraint(
            ["phase_id"],
            ["phases.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("phase_id", "sort_order", name="uq_tasks_phase_sort"),
    )
    # 业务索引（doc/02 2.13）：加速按 goal/theme/phase 过滤与 draft 检索
    op.create_index("idx_themes_goal", "themes", ["goal_id"])
    op.create_index("idx_phases_theme", "phases", ["theme_id", "sort_order"])
    op.create_index("idx_tasks_phase", "tasks", ["phase_id", "sort_order"])
    op.create_index("idx_tasks_status", "tasks", ["status"])
    op.create_index("idx_drafts_user", "drafts", ["user_id", "story_type", "status"])
    op.create_index("idx_drafts_expires", "drafts", ["expires_at"])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # 先删索引再删表（索引依赖表存在）
    op.drop_index("idx_drafts_expires", table_name="drafts")
    op.drop_index("idx_drafts_user", table_name="drafts")
    op.drop_index("idx_tasks_status", table_name="tasks")
    op.drop_index("idx_tasks_phase", table_name="tasks")
    op.drop_index("idx_phases_theme", table_name="phases")
    op.drop_index("idx_themes_goal", table_name="themes")
    op.drop_table("tasks")
    op.drop_table("phases")
    op.drop_table("themes")
    op.drop_table("goals")
    op.drop_table("drafts")
    # ### end Alembic commands ###
